## Server Properties
server:
  port: ${PORT:5000}

spring:
  datasource:
    url: ${BACKEND_DATABASE_URL}
    username: ${BACKEND_DATABASE_USERNAME}
    password: ${BACKEND_DATABASE_PASSWORD}
    initialization-mode: always
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
